import Head from "next/head";

import Navbar from "./navbar";
// import Footer from "./footer";

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <Head>
                <title>Jesse Marr | Resume</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <Navbar />
                <div className="flex min-h-screen flex-col items-center justify-center">
                    {children}
                </div>
                {/* <Footer /> */}
            </main>
        </>
    );
}
